---
title: "Simple Test coexistence"
author: "XX"
date: "4 juin 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(cowplot)
```

## R Markdown

```{r}
devtools::load_all()
#### Keep stable for all
patches  <- 25   # Number of patches
species  <- 25   # Number of species
time     <- 150	 # Length of model run (generations)
initpop  <- 150   # initial population size
n_traits <- 1    # number of traits
k        <- 1.45 # Niche height
c        <- 10 # Niche breadth

# Competition + Dispersion coefficients
A =  0.0005	# Alpha scalar 
d = 0.5 # Dispersal percentage

# Generate environment
env <- 1:patches

composition <- array(NA, dim = c(patches, species, time),
                     dimnames = list(paste0("patches", 1:patches),
                                     paste0("species", 1:species),
                                     paste0("time", 1:time))) #where values = N
names(env) <- dimnames(composition)[[1]]

composition[,,"time1"] <- initpop # N

# Generate traits
traits <- generate_traits(species,
                          rep(min(env), n_traits),
                          rep(max(env), n_traits))

# Single trait competition, single trait growth, single trait both -------------
# Goal: compare between the three above-mentioned cases

## Single Trait Competition
trait_type = c(trait1 = "A")
single_trait_compet = multigen(traits = traits, trait_type = trait_type,
                               env = env, time = time, species = species,
                               patches = patches, composition = composition,
                               A = A, d = d, k = k, c = c)
single_trait_compet_final = ifelse(single_trait_compet$compo[,,time] < 2, 0, single_trait_compet$compo[,,time])

## Single Trait Growth
trait_type = c(trait1 = "R")
single_trait_growth = multigen(traits = traits, trait_type = trait_type,
                               env = env, time = time, species = species,
                               patches = patches, composition = composition,
                               A = A, d = d, k = k, c = c)
single_trait_growth_final = ifelse(single_trait_growth$compo[,,time] < 2, 0,
                                   single_trait_growth$compo[,,time])

## Both
trait_type = c(trait1 = "RA")
single_trait_both = multigen(traits = traits, trait_type = trait_type,
                             env = env, time = time, species = species,
                             patches = patches, composition = composition,
                             A = A, d = d, k = k, c = c)

single_trait_both_final = ifelse(single_trait_both$compo[,,time] < 2, 0,
                                 single_trait_both$compo[,,time])
```

```{r}
p5_comp = plot_patch(single_trait_compet$compo, 5, 100) +
    labs(subtitle = "Competition")
p5_grow = plot_patch(single_trait_growth$compo, 5, 100) +
    labs(subtitle = "Growth")
p5_both = plot_patch(single_trait_both$compo,   5, 100) +
    labs(subtitle = "Both")

p15_comp = plot_patch(single_trait_compet$compo, 15, 100) +
    labs(subtitle = "Competition")
p15_grow = plot_patch(single_trait_growth$compo, 15, 100)  +
    labs(subtitle = "Growth")
p15_both = plot_patch(single_trait_both$compo,   15, 100) +
    labs(subtitle = "Both")

plot_patches = plot_grid(p5_grow, p5_comp, p5_both, p15_grow, p15_comp,
                         p15_both, ncol = 3, nrow = 2)
plot_patches
```

## Compute CWM & CWV

```{r}
compute_cwm = function(simulation_routine, trait_df = traits) {
    cwm_df = (simulation_routine$compo[,,150] / rowSums(simulation_routine$compo[,,150])) %*% trait_df
    
    cwm_df = as.data.frame(cwm_df)
    cwm_df = tibble::rownames_to_column(cwm_df, "patch")
    cwm_df$env      = seq(patches)
    
    return(cwm_df)
}

both_cwm = compute_cwm(single_trait_both, traits)
colnames(both_cwm)[2] = c("both_cwm")
growth_cwm = compute_cwm(single_trait_growth, traits)
colnames(growth_cwm)[2] = c("growth_cwm")
compet_cwm = compute_cwm(single_trait_compet, traits)
colnames(compet_cwm)[2] = c("compet_cwm")

all_cwm = merge(both_cwm, growth_cwm, c("patch", "env"))
all_cwm = merge(all_cwm, compet_cwm, c("patch", "env"))
all_cwm = tidyr::gather(all_cwm, "cwm_type", "cwm_value", dplyr::contains("cwm"))

plot_cwm = ggplot(all_cwm, aes(env, cwm_value, color = cwm_type)) +
    geom_abline(slope = 1, intercept = 0) +
    geom_point() +
    labs(x = "Environmental Value",
         y = "Community Weighted Mean",
         subtitle = "Timestep: 150, Trait Both") +
    scale_color_discrete(labels = c(pred_cwm = "Optimal\nTrait",
                                    trait1   = "Obs. CWM")) +
    theme_bw()
plot_cwm
```

