---
title: "Targeted set of scenarios"
author:
    - Pierre Denelle, Matthias Grenié, Cyrille Violle, François Munoz and Caroline M. Tucker
date: "`r format(Sys.time(), '%d %B %Y')`"
output: pdf_document
vignette: >
    %\VignetteIndexEntry{Full equation of the model}
    %\VignetteEncoding{UTF-8}
    %\VignetteEngine{knitr::rmarkdown}
editor_options: 
    chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE,
                      fig.width = 8, fig.height = 10.5, cache = TRUE,
                      cache.lazy = FALSE, eval = FALSE)

# Packages ---------------------------------------------------------------------
suppressPackageStartupMessages({
    suppressWarnings({
        library("tidyverse")
        library("cowplot")
        library("furrr")
        library("lme4")
        
        devtools::load_all()
    })
})

# Functions --------------------------------------------------------------------

get_predictions_along_environment = function(var_perf_df, scenario) {
    given_df = var_perf_df %>%
        filter(scenario == !!scenario)
    
    list(mono = given_df %>%
             filter(A == 0, B == 1e-4, H == 0, k == 1.2) %>%
             get_perf_weighted(),
         cwm_hierarchical = given_df %>%
             filter(A == 0, B == 1e-4, H == 0.5, k == 1.2) %>%
             get_perf_weighted(),
         cwm_limiting = given_df %>%
             filter(A == 1e-5, B == 1e-4, H == 0, k == 1.2) %>%
             get_perf_weighted()) %>%
        bind_rows(.id = "pred_type") %>%
        ungroup() %>%
        mutate(pred_type = factor(pred_type, c("mono",
                                               "cwm_hierarchical",
                                               "cwm_limiting")),
               trait_cor = factor(trait_cor, c("negcor",
                                               "uncor",
                                               "poscor"))) %>%
        gather("trait_name", "trait_value", trait1_weight, trait2_weight)
}

get_perf_weighted = function(given_df) {
    given_df %>%
        group_by(A, B, H, k, scenario, trait_cor, seed, patch) %>%
        summarise_at(vars(tidyselect::matches("trait\\d*")),
                     .funs = list(weight = ~weighted.mean(., N150)))
}

plot_predictions_along_environment = function(perf_along_env_df) {
    perf_along_env_df %>%
        ggplot(aes(patch, trait_value, color = pred_type)) +
        geom_abline(slope = 1, intercept = 0, linetype = 2) +
        geom_line(aes(group = interaction(seed, pred_type)), size = 1,
                  alpha = 1/6) +
        geom_smooth(method = "lm", se = FALSE, size = 1.2) +
        ggpmisc::stat_poly_eq(formula = y ~ x, parse = TRUE, size = 3,
                              aes(label = ..eq.label..))
        facet_grid(vars(trait_cor),
                   vars(trait_name),
                   labeller = labeller(
                       trait_cor = c(negcor = "Negative Correlation",
                                     uncor  = "Uncorrelated",
                                     poscor = "Positive Correlation"),
                       trait_name = c(trait1_weight = "Trait 1",
                                      trait2_weight = "Trait 2"))) +
        ylim(0, 25) +
        colorblindr::scale_color_OkabeIto(
            labels = c(indiv            = "Individual",
                       mono             = "Monoculture",
                       cwm_hierarchical = "CWM with\nHierarch. Compet.",
                       cwm_limiting     = "CWM with\nLimit. Sim.")) +
        labs(x = "Environment",
             y = "Trait",
             color = "Performance\nType") +
        theme(aspect.ratio = 1,
              legend.position = "top")
}

plot_mod_estimate_along_env = function(mod_df) {
    mod_df %>%
        mutate(br = map(lin_mod, broom::tidy, conf.int = TRUE)) %>%
        unnest(br) %>%
        filter(effect == "fixed") %>%
        ggplot(aes(pred_type, estimate, color = trait_name)) +
        geom_hline(yintercept = 0, linetype = 2) +
        geom_pointrange(aes(ymin = conf.low,
                            ymax = conf.high),
                        position = position_dodge(0.5)) +
        facet_grid(vars(trait_cor), vars(term),
                   labeller = labeller(
                       trait_cor = c(negcor = "Negative Correlation",
                                     uncor  = "Uncorrelated",
                                     poscor = "Positive Correlation"),
                       term = c(`(Intercept)` = "Intercept",
                                trait_value   = "slope")),
                   scales = "free_x") +
        coord_flip() +
        labs(x = "Slope Estimate",
             y = "Prediction Type",
             subtitle = "Estimate with 95% CI intervals") +
        scale_x_discrete(
            labels = c(mono             = "Monoculture",
                       cwm_hierarchical = "CWM with\nHierarch. Compet.",
                       cwm_limiting     = "CWM with\nLimit. Sim.")) +
        scale_color_discrete(labels = c(trait1_weight = "Trait 1",
                                      trait2_weight = "Trait 2"))
}
# Other ------------------------------------------------------------------------
theme_set(theme_bw(16))

plan(multiprocess, workers = 8)
```

Actual scenarios

```{r parameters}
list_A = c(0, 10^-(c(5)))
list_k = c(1.2, 1.5)
list_B = c(0, 10^-(c(2)))
list_H = c(0, 0.5)
n_seed = 2
n_patches = 25
n_species = 100
n_gen = 50
```

```{r scenarios}
weights = c(0, 100)
scenar_df = expand.grid(R = weights, A = weights, H = weights) %>%
    as_tibble() %>%
    mutate(scenar_name   = paste0("R", R, "A", A, "H", H),
           trait_weights = purrr::pmap(list(R, A, H),
                                       ~create_trait_weights(..1, ..2, ..3, 2)))
scenar_list = scenar_df$trait_weights
names(scenar_list) = scenar_df$scenar_name
```

```{r get_traits}
# Generate trait matrices for each seed
fixed_coef = 0.3
trait_seeds = lapply(seq(n_seed), function(seed) {
    set.seed(seed)
    uncor  = generate_cor_traits(n_patches, n_species, 1, cor_coef = 0)
    set.seed(seed)
        poscor = generate_cor_traits(n_patches, n_species, 1,
                                     cor_coef = fixed_coef)
    set.seed(seed)
        negcor = generate_cor_traits(n_patches, n_species, 1,
                                     cor_coef = -fixed_coef)
    list(poscor = poscor,
         uncor  = uncor,
         negcor = negcor)
})
```

```{r simulation}
# multidimensional matrix
composition <- array(NA, dim = c(n_patches, n_species, n_gen),
                     dimnames = list(paste0("patches", seq(n_patches)),
                                     paste0("species", seq(n_species)),
                                     paste0("time", seq(n_gen))))

composition[,,1] = 50

# Actual simulations -----------------------------------------------------------
param_sets = list(
    run_n = seq(n_seed),
    A     = list_A,
    k     = list_k,
    B     = list_B, 
    H     = list_H) %>%
    cross()

tictoc::tic()

plan(multiprocess)
var_param = future_map(param_sets, function(x) {
    suppressMessages({
        devtools::load_all()
    })

    meta_simul(seed_number = x$run_n,
               given_k = x$k,
               given_A = x$A,
               given_B = x$B,
               given_scenars = scenar_list,
               given_H = x$H,
               given_traits = trait_seeds[[x$run_n]],
               given_h_fun = "sum",
               given_di_thresh = 24,
               given_env = 1:25,
               given_composition = composition,
               given_d = 0.05)
}, .progress = TRUE)
tictoc::toc()

# All Traits -------------------------------------------------------------------

full_trait_df = map_dfr(trait_seeds, function(x) {
    map_dfr(x, ~.x %>%
                as.data.frame() %>%
                rownames_to_column("species"),
            .id = "trait_cor")
},.id = "seed") %>%
    mutate(seed = as.integer(seed))

# Extract performances indices -------------------------------------------------

tictoc::tic()
var_perfs = future_map_dfr(unlist(var_param, recursive = FALSE),
                          ~extract_performances_from_simul(.x, trait_seeds,
                                                           TRUE))
tictoc::toc()

saveRDS(var_param, "../inst/job_data/other_simuls.Rds")
saveRDS(var_perfs, "../inst/job_data/other_simuls_perfs.Rds")

var_perfs = var_perfs %>%
    mutate(scenario = case_when(R_scenar == 100 & A_scenar == 100 &
                                    H_scenar == 100 ~ "R100A100H100",
                                R_scenar ==  50 & A_scenar ==   0 &
                                    H_scenar ==   0 ~ "R50A0H0",
                                R_scenar ==   0 & A_scenar == 100 &
                                    H_scenar == 100 ~ "R0A100H100",
                                R_scenar ==  50 & A_scenar ==  50 &
                                    H_scenar ==  50 ~ "R50A50H50")) %>%
    inner_join(full_trait_df, by = c("trait_cor", "seed", "species"))



n_simul = length(param_sets)
```

```{r first_scenario}
first_scenar = get_predictions_along_environment(var_perfs, "R100A100H100")

fig_first_scenar = first_scenar %>%
    filter(trait_name == "trait2_weight", trait_cor == "uncor") %>%
    plot_predictions_along_environment() +
    labs(title = "Trait 2 contributing to all processes") +
    theme(strip.text = element_blank())

first_mod = first_scenar %>%
    filter(trait_cor == "uncor", trait_name == "trait2_weight") %>%
    nest(-pred_type) %>%
    mutate(lin_mod = map(data, ~lmer(patch ~ trait_value + (1|seed), data =.)))

# Save files -------------------------------------------------------------------
ggsave("perf_environment_trait2_only.pdf", fig_first_scenar,
       width = 15, height = 15.5, units = "cm")
saveRDS(first_mod, "inst/lm_trait2_only.Rds")
```

```{r second_scenario}
second_scenar = get_predictions_along_environment(var_perfs, "R50A0H0")

fig_second_scenar = second_scenar %>%
    plot_predictions_along_environment() +
    labs(title = "Both Traits contributing 50% to Growth")

second_mod = second_scenar %>%
    nest(-trait_name, -trait_cor, -pred_type) %>%
    mutate(lin_mod = map(data, ~lme4::lmer(patch ~ trait_value + (1|seed),
                                           data =.)))

fig_second_mod = plot_mod_estimate_along_env(second_mod)

# Save files -------------------------------------------------------------------
ggsave("perf_environment_both_traits_only_growth.pdf", fig_second_scenar,
       width = 17, height = 25.5, units = "cm")
saveRDS(second_mod, "inst/lm_both_traits_only_growth.Rds")
```


```{r third_scenario}
third_scenar = get_predictions_along_environment(var_perfs, "R0A100H100")

fig_third_scenar = third_scenar %>%
    plot_predictions_along_environment() +
    labs(title = "Trait 1 = 100% Growth; Trait 2 = 100% Competition")

third_mod = third_scenar %>%
    nest(-trait_name, -trait_cor, -pred_type) %>%
    mutate(lin_mod = map(data, ~lme4::lmer(patch ~ trait_value + (1|seed), data =.)))

fig_third_mod = plot_mod_estimate_along_env(third_mod)


# Save files -------------------------------------------------------------------
ggsave("perf_environment_trait1_growth_trait2_competition.pdf", fig_third_scenar,
       width = 17, height = 25.5, units = "cm")
saveRDS(third_mod, "inst/lm_trait1_growth_trait2_competition.Rds")
```

```{r fourth_scenario}
fourth_scenar = get_predictions_along_environment(var_perfs, "R50A50H50")

fig_fourth_scenar = fourth_scenar %>%
    plot_predictions_along_environment() +
    labs(title = "Both Traits contributing equally to all processes")

fourth_mod = fourth_scenar %>%
    nest(-trait_name, -trait_cor, -pred_type) %>%
    mutate(lin_mod = map(data, ~lme4::lmer(patch ~ trait_value + (1|seed), data =.)))

fig_fourth_mod = plot_mod_estimate_along_env(fourth_mod)

# Save files -------------------------------------------------------------------
ggsave("perf_environment_both_traits_all.pdf", fig_fourth_scenar,
       width = 17, height = 25.5, units = "cm")
saveRDS(fourth_mod, "inst/lm_both_traits_all.Rds")
```


Fit big model

```{r fit_big_model}
big_mod = var_perfs %>%
    group_by(k, A, B, H, trait_cor, scenario, seed, patch) %>%
    summarise_at(vars(tidyselect::matches("trait[12]")),
                 .funs = list(weight = ~weighted.mean(., N150))) %>%
    gather("trait_name", "trait_value", contains("weight")) %>%
    ungroup()

single_mod = big_mod %>%
    filter(trait_name == "trait2_weight", scenario == "R100A100H100",
           trait_cor == "uncor") %>%
    nest(-trait_name, -scenario, -trait_cor) %>%
    mutate(data = map(data, ~mutate_at(.x,
                                       c("k", "A", "B", "H"),
                                       scale)),
           lin_mod = map(data, ~lme4::lmer(trait_value - patch ~  (k + A +
                                                   B + H)^2 + (1|seed),
                                               data = .)))
```


```{r obs_th_growth}
fig_growth = var_perfs %>%
    filter(B == 1e-4, A == 1e-5, H == 0, seed == 5) %>%
    filter(species %in% paste0("species", c(1, 50, 99)), scenario == "R100A100H100", trait_cor == "uncor", k == 1.5) %>%
    tidyr::gather("growth_type", "growth_value", env_growth_rate, max_growth_rate) %>%
    ggplot(aes(patch, growth_value, color = species, group = interaction(growth_type, species))) +
    geom_line(size = 1) +
    facet_wrap(~growth_type, scales = "free", labeller = as_labeller(c(env_growth_rate = "Theoretical Growth Rate", max_growth_rate = "Realized Growth Rate"))) +
    theme_bw() +
    labs(x = "Environment", y = "Growth Rate") +
    theme(legend.position = "top")

ggsave("theoretical_vs_observed_growth_rate.pdf", fig_growth,
       width = 15, height = 14.5, units = "cm")
```


```{r compare_all_performance_values}
var_perfs = readRDS("inst/caro_var_perfs.Rds")

var_cwm = var_perfs %>%
    group_by(k, A, B, H, scenario, trait_cor, seed, patch) %>%
    summarise_at(vars(dplyr::matches("trait[12]")),
                 .funs = list(cwm = ~weighted.mean(., N150)))

# Get indiviudal estimates
var_individuals = var_perfs %>%
    filter(A == 0, H == 0, B == 0) %>%
    select(-A, -H, -B) %>%
    group_by(k, scenario, trait_cor, seed, species) %>%
    filter(N150 == max(N150)) %>%
    rename(individual_optim = patch) %>%
    select(group_vars(.), individual_optim, trait1, trait2) %>%
    rename(individual_trait1 = trait1,
           individual_trait2 = trait2)

# Get monoculture estimates
var_monocult = var_perfs %>%
    filter(A == 0, H == 0, B != 0) %>%
    select(-A, -H) %>%
    group_by(k, B, scenario, trait_cor, seed, species) %>%
    filter(N150 == max(N150)) %>%
    rename(monocult_optim = patch) %>%
    select(group_vars(.), monocult_optim, trait1, trait2) %>%
    rename(monocult_trait1 = trait1,
           monocult_trait2 = trait2)

# Get polyculture estimates
var_polycult = var_perfs %>%
    filter(A != 0 | H != 0, B != 0) %>%
    group_by(k, A, B, H, scenario, trait_cor, seed, species) %>%
    filter(N150 == max(N150)) %>%
    rename(polycult_optim = patch) %>%
    select(group_vars(.), polycult_optim, trait1, trait2) %>%
    rename(polycult_trait1 = trait1,
           polycult_trait2 = trait2)
```


```{r plot_performance_values}
var_individuals %>%
    ungroup() %>%
    ggplot(aes(individual_optim, individual_trait2)) +
    geom_abline(slope = 1, intercept = 0, linetype = 2) +
    geom_point(alpha = 1/30) +
    geom_smooth(aes(group = seed), se = FALSE, method = "lm", color = "black") +
    geom_smooth(se = FALSE, method = "lm") +
    facet_grid(vars(k), vars(scenario, trait_cor), labeller = label_both)

var_monocult %>%
    ungroup() %>%
    filter(scenario != "R50A0H0") %>%
    ggplot(aes(monocult_optim, monocult_trait2)) +
    geom_abline(slope = 1, intercept = 0, linetype = 2) +
    geom_point(alpha = 1/30) +
    geom_smooth(se = FALSE, method = "lm", aes(group = seed), color = "black", alpha = 1/4) +
    geom_smooth(se = FALSE, method = "lm") +
    facet_grid(vars(k, B), vars(scenario, trait_cor), labeller = label_both)

var_polycult %>%
    filter(trait_cor == "uncor") %>%
    ungroup() %>%
    ggplot(aes(polycult_optim, polycult_trait2)) +
    geom_abline(slope = 1,intercept = 0, linetype = 2) +
    geom_point(alpha = 1/30) +
    geom_smooth(aes(group = seed), method = "lm", se = FALSE, alpha = 1/5,
                color = "black") +
    geom_smooth(method = "lm", se = FALSE) +
    facet_grid(vars(k, B), vars(A, H), labeller = label_both) +
    theme(aspect.ratio = 1)

var_cwm %>%
    ungroup() %>%
    ggplot(aes(patch, trait2_cwm)) +
    geom_abline(slope = 1, intercept = 0, linetype = 2) +
    geom_line(aes(group = seed), color = "black", alpha = 1/4) +
    geom_line() +
    facet_grid(vars(k, B), vars(A, H, scenario, trait_cor),
               labeller = label_both) +
    theme(aspect.ratio = 1)
```

```{r combine_perf_values}
prep_cwm = var_cwm %>%
    filter(A != 0 | H != 0, B != 0) %>%
    ungroup() %>%
    mutate(pred_type = "cwm") %>%
    rename(trait1 = trait1_cwm,
           trait2 = trait2_cwm)


prep_polycult = var_polycult %>%
    ungroup() %>%
    rename(trait1 = polycult_trait1,
           trait2 = polycult_trait2,
           patch  = polycult_optim) %>%
    select(-species) %>%
    mutate(pred_type = "polycult")

prep_monocult = prep_cwm %>%
    distinct(A, H) %>%
    mutate(df = map2(A, H, ~var_monocult %>%
                         ungroup() %>%
                         select(-species) %>%
                         rename(patch  = monocult_optim,
                                trait1 = monocult_trait1,
                                trait2 = monocult_trait2) %>%
                         mutate(pred_type = "monocult"))) %>%
    unnest(df)

prep_individual = prep_cwm %>%
    distinct(A, B, H) %>%
    mutate(df = map(A, ~var_individuals %>%
                        ungroup() %>%
                        select(-species) %>%
                        rename(patch  = individual_optim,
                               trait1 = individual_trait1,
                               trait2 = individual_trait2) %>%
                        mutate(pred_type = "individual"))) %>%
    unnest(df)

prep_all = bind_rows(prep_cwm,
                     prep_polycult,
                     prep_monocult,
                     prep_individual)
```

```{r final_plot}
prep_all %>%
    filter(trait_cor == "uncor", scenario != "R50A0H0") %>%
    ggplot(aes(patch, trait2, color = pred_type)) +
    geom_abline(slope = 1, intercept = 0, linetype = 2) +
    geom_line(stat = "smooth", method = "lm", se = FALSE,
              aes(group = interaction(pred_type, seed)), alpha = 1/5) +
    geom_line(stat = "smooth", method = "lm", se = FALSE, alpha = 2/3) +
    facet_grid(vars(k, B), vars(scenario, A, H), labeller = label_both) +
    labs(x = "Environment", y = "Performance")
```
