version: 2
jobs:
  build:
    working_directory: ~/main
    branches:
      only:
        - master
        - add_circle_ci
    docker:
      - image: appsilon/ci-base:1.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps1-{{ .Branch }}-{{ checksum "DESCRIPTION" }}
            - deps1-{{ .Branch }}
            - deps1-
      - run:
          name: Install Dependencies
          command: |
            R -e 'devtools::install_deps(dependencies = TRUE)'
            R -e "devtools::install_github('MangoTheCat/goodpractice')"
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "DESCRIPTION" }}
          paths:
            - "/usr/local/lib/R/site-library"
      - run:
          name: Build package
          command: R CMD build . --no-build-vignettes
      - run:
          name: Check package
          command: R CMD check "${PKG_TARBALL}" --as-cran --no-manual --no-vignettes
      - run:
          name: Check Package, Coverage & Good Practice
          command: |
            Rscript -e 'message(devtools::check_failures(path = '${RCHECK_DIR}'))'
            Rscript -e 'covr::codecov()'
            Rscript -e "goodpractice::gp()"
      - store_artifacts:
          path: man/
          destination: man
