version: 2
jobs:
  build:
    working_directory: ~/main
    branches:
      only:
        - master
        - add_circle_ci
    docker:
      - image: appsilon/ci-base:1.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps1-{{ .Branch }}-{{ checksum "DESCRIPTION" }}
            - deps1-{{ .Branch }}
            - deps1-
      - run:
          command: |
            R -e 'devtools::install_deps(dependencies = TRUE)'
            R -e "devtools::install_github('MangoTheCat/goodpractice')"
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "DESCRIPTION" }}
          paths:
            - "/usr/local/lib/R/site-library"
      - run:
          command: |
            R -e 'devtools::check()'
            R -e 'covr::codecov()'
      - store_artifacts:
          path: man/
          destination: man
